# exp type
experiment: interpolation

# data params
N: 5000                  # data points
tr_sample: 0.005           # % to train on

# model params
r1d: 100                  # first layer width
l2d: 50                  # second layer width
r2d: 100                 # third layer width
epochs: 100              # epochs to train for
lr: 1e-3                 # learning rate
scale: 0.6               # scalar for regularization
regularization: 2        # regularization method