# exp type
experiment: sparsity

# data params
N: 5000                  # data points
tr_sample: 0.05           # % to train on

# model params
r1d: 100                  # first layer width
l2d: 50                  # second layer width
r2d: 100                 # third layer width
epochs: [50, 100, 200, 400, 750, 1250, 1750, 2500]   # epochs to train for
lr: 1e-3                 # learning rate
scale: 0.3               # scalar for regularization
regularization: 2        # regularization method

